### ISSUE TITLE
Individual Songs Don't Seem To Play Upon Request

### ISSUE THREAD

**Issue by ghostbuster84** [LostLightProjects/jellyfin-skill#2]
When asking "Hey Mycroft, Play Song ______ From Jellyfin"  It says it can't find or play _______. I am working on figuring this out.

**Comment by meonkeys** [comment]
This seems to work for me intermittently.

**Comment by ghostbuster84** [comment]
I have not been able to get it to work either on Linux PC or picroft with google AIY voicekit

**Comment by ghostbuster84** [comment]
Still can't seem to get it to work. Will be doing more testing to sort this out.

**Comment by ghostbuster84** [comment]
Figured it out! The Music has to have the metadata filled out for it to work. All fixed and works actually quite nicely now.
