### ISSUE TITLE
License

### ISSUE THREAD

**Issue by strugee** [LostLightProjects/jellyfin-skill#7]
Currently in most jurisdictions it is actually a violation of copyright law to run this skill on a Mycroft installation since it's missing a license. It would be super great if you would relicense this project to be open source/[freedom-respecting software](https://www.gnu.org/philosophy/free-sw.html).

https://choosealicense.com/ can help with this. It also includes [a page](https://choosealicense.com/no-permission/) on why not having a license might not be what you intended. Let me know if you have any questions.

You'll also have to get permission from the other copyright holders to do this. Personally, I would prefer a copyleft license like the GPLv3 (or v2 if you must) or AGPL but am also ok with MIT or Apache 2.0 or a BSD license.

CC @meonkeys and @ghostbuster84 who are listed on https://github.com/LostLightProjects/jellyfin-skill/graphs/contributors. Also CC @rickyphewitt and @tuxfoo who are listed in the README's credits section as having written code this is descended from. Note that it seems @tuxfoo has already approved licensing as GPLv2: https://github.com/tuxfoo/jellyfin-skill/blob/master/LICENSE.md

**Comment by ghostbuster84** [comment]
Good to know, I will look into that eventually

**Comment by strugee** [comment]
Actually wait I totally didn't think enough while I was writing the description. Because @tuxfoo's code is GPLv2, your code MUST also be GPLv2. See "same license" under "conditions" on https://choosealicense.com/licenses/gpl-2.0/.

Sorry, I know licensing isn't the most fun part of software development and can be kinda boring :/ but it's an important one.
